#:schema node_modules/wrangler/config-schema.json
name = "domain-checker"
compatibility_date = "2025-03-17"
compatibility_flags = ["nodejs_compat"]
# Nitro cloudflare-pages-static emits the static site into dist/
pages_build_output_dir = "dist"
